
import "./globals.css";
import { Inter } from "next/font/google";
import Navbar from "@/components/Navbar.js";
import Tabs from "@/components/Tabs.js";
import Sidebar from "@/components/Sidebar.js";
import { Providers } from "@/lib/Providers.js";

const inter = Inter({
  subsets: ["latin"],
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en" suppressHydrationWarning>
      <body className={inter.className}>
        <Providers>
          <div className="flex flex-col h-screen overflow-hidden">
            <Navbar />
            <div className="flex-1  flex flex-col md:grid md:grid-cols-5">
              <Tabs/>
              <Sidebar/>
              <div className="col-span-4 flex-1">

              {children}
              </div>
            </div>
          </div>
        </Providers>
      </body>
    </html>
  );
}
